import React, { useState } from 'react';
import './home.css';
import Search from './layouts/Search';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {faWindowRestore, faDoorClosed, faFileAlt, faFan, faPeopleRoof } from '@fortawesome/free-solid-svg-icons';

function Home() {
  const [activeCategory, setActiveCategory] = useState(0); 

  const categories = [
    {
        title: 'PVC Windows',
        description: 'PVC Windows!',
        descriptiondetails: 'Unplasticized polyvinyl chloride (uPVC) is a type of hard plastic material widely used in windows and doors. Pollution, moisture, rust, and mold are all ineffective on the material. This makes uPVC windows a more durable choice than wood windows.',
        imageUrl: 'https://res.cloudinary.com/dhxhxvkkx/image/upload/v1711082741/fdp6gz43gnm913nsqtws.jpg',
        icon: faWindowRestore,
      },
      {
        title: 'PVC Doors',
        description: 'PVC Doors!',
        descriptiondetails: 'UPVC is proven to offer excellent performance and durability; it is long-lasting and requires very little maintenance making it the perfect material for doors and windows. It is also recognized for its thermal efficiency, sound insulation, and great value for money.',
        imageUrl: 'https://res.cloudinary.com/dhxhxvkkx/image/upload/v1711082741/um2emamliputaqzcdo6l.jpg',
        icon: faDoorClosed,
      },
      {
        title: 'PVC Sheets',
        description: 'PVC Sheets!',
        descriptiondetails: 'Eco-friendly and non-toxic expanded PVC sheets provide strength, durability, and flame and chemical resistance while remaining easy to cut and shape.',
        imageUrl: 'https://res.cloudinary.com/dhxhxvkkx/image/upload/v1711082741/dfzjv1gywywfkx1pkhoy.jpg',
        icon: faFileAlt,
      },
      {
        title: 'PVC Ventilation',
        description: 'PVC Ventilation!',
        descriptiondetails: 'PVC Ventilation Duct is a corrosion-resistant, effective, and lightweight solution for industrial and institutional ventilation systems. IPEX Ventilation PVC and CPVC Duct pipes safely convey exhaust fumes generated by various industrial processes.',
        imageUrl: 'https://res.cloudinary.com/dhxhxvkkx/image/upload/v1711082741/htfmfezrek8hxewmdc8n.jpg',
        icon: faFan,
      },
      {
        title: 'PVC Cooling Window Blinds',
        description: 'PVC Cooling Window Blinds!',
        descriptiondetails: 'PVC blinds provide daytime privacy while still allowing natural light and visibility on the inside. It can lower interior temperature as much as possible. PVC blinds are designed to be long lasting and durable in any climatic changes.',
        imageUrl: 'https://res.cloudinary.com/dhxhxvkkx/image/upload/v1711082741/kpmpjrxhdw6xjc45uns6.jpg',
        icon: faPeopleRoof,
      },
      {
        title: 'PVC Roofs',
        description: 'Information and Safety Tips for Traveling',
        descriptiondetails: 'Made from polyvinyl chloride (or in laymans terms, plastic), PVC is a great single-ply roofing solution. It is made from a lower percentage of oil and petroleum than thermoplastic polyolefin (TPO) or ethylene propylene diene terpolymer (EPDM).',
        imageUrl: 'https://res.cloudinary.com/dhxhxvkkx/image/upload/v1711082741/tbd3jjwkifs4jz0km9cb.jpg',
        icon: faPeopleRoof,
      },
    ];
  const handleCategoryClick = (index) => {
    setActiveCategory(index);
  };

  return (
    <div>
      <div className="main-banner">
        <div className="container">
          <div className="row">
            <div className="col-lg-12">
              <div className="top-text header-text">
                <h6>Welcome To Ganapathy Traders - A Whole Sale PVC Store</h6>
                <h2>Find Your Products Here</h2>
                <div className="see">
                    <div className="col-12 col-md-6 mt-2 mt-md-0">
            <Search/>
         </div></div>
              </div>
            </div>
            <div className="col-lg-12">
            </div>
            <div className="col-lg-10 offset-lg-1">
              <ul className="categories">
                <li><a href="/productspro"><span className="icon"><FontAwesomeIcon icon={faWindowRestore} /></span> PVC Windows</a></li>
                <li><a href="/productspro"><span className="icon"><FontAwesomeIcon icon={faDoorClosed} /></span>PVC Doors</a></li>
                <li><a href="/productspro"><span className="icon"><FontAwesomeIcon icon={faFan} /></span> PVC Ventilation</a></li>
                <li><a href="/productspro"><span className="icon"><FontAwesomeIcon icon={faDoorClosed} /></span> PVC Cooling Blinds</a></li>
                <li><a href="/productspro"><span className="icon"><FontAwesomeIcon icon={faPeopleRoof} /></span> PVC Roofs</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="popular-categories">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="section-heading">
            <h2>Popular Categories</h2>
            <h6>Check Them Out</h6>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="naccs">
            <div class="grid">
              <div class="row">
                <div class="col-lg-3">
                  <div class="menu">
                  {categories.map((category, index) => (
                <div key={index} className={index === activeCategory ? 'thumb active' : 'thumb'} onClick={() => handleCategoryClick(index)}>
                  <span className="icon">
                  <FontAwesomeIcon icon={category.icon} />
                  </span>
                  {category.title}
                </div>
              ))}
                    
                  </div>
                </div> 
                <div class="col-lg-9 align-self-center">
                  <ul class="nacc">
                  {categories.map((category, index) => (
                <li key={index} className={index === activeCategory ? 'active' : ''}>
                      <div>
                        <div class="thumb">
                        <div className="row">
                      <div className="col-lg-5 align-self-center">
                        <div className="left-text">
                          <h4>{category.description}</h4>
                          <p>{category.descriptiondetails}</p>
                          <div className="main-white-button">
                            <a href="/productspro"><i className="fa fa-eye"></i> Discover More</a>
                          </div>
                        </div>
                      </div>
                      <div className="col-lg-7 align-self-center">
                        <div className="right-image">
                          <img src={category.imageUrl} alt=""/>
                        </div>
                      </div>
                    </div>
                        </div>
                      </div>
                    </li>
                    ))}
                  </ul>
                </div>          
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    </div>
  );
}

export default Home;
